# Generated by Django 4.0.3 on 2022-03-08 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_customuser_district_alter_customuser_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='facility',
            name='kind',
            field=models.CharField(choices=[('PHC', 'PHC'), ('CHC', 'CHC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='familydetail',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='expired_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='pallative_phase',
            field=models.CharField(choices=[('Stable', 'Stable'), ('Unstable', 'Unstable'), ('Deteriorating', 'Deteriorating'), ('Dying', 'Dying')], default='Stable', max_length=100),
        ),
    ]
