# Generated by Django 4.0.3 on 2022-03-09 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_customuser_phone_alter_facility_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
