# Generated by Django 4.0.3 on 2022-03-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_patient_facility_alter_familydetail_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydetail',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.patient'),
        ),
        migrations.AlterField(
            model_name='familydetail',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
