# Generated by Django 4.0.3 on 2022-03-10 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_treatment_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('icds_code', models.CharField(max_length=35)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.patient')),
                ('treated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
