# Generated by Django 4.0.3 on 2022-03-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_remove_visitdetails_note_visitschedule_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
