# Generated by Django 4.0.3 on 2022-03-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_treatment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetails',
            name='visit_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.visitschedule'),
        ),
    ]
