# Generated by Django 4.0.3 on 2022-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_visitdetails_visit_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitdetails',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
