# Generated by Django 4.0.3 on 2022-03-11 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_visitdetails_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentnotes',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.treatment'),
        ),
        migrations.AlterField(
            model_name='treatmentnotes',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.visitdetails'),
        ),
    ]
