# Generated by Django 4.0.3 on 2022-03-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_treatmentnotes_treatment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentnotes',
            name='notes',
        ),
        migrations.AddField(
            model_name='treatmentnotes',
            name='heading',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
