# Generated by Django 4.0.3 on 2022-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_customuser_schedule_alert_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitschedule',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
